CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, 
	name VARCHAR(100), phone VARCHAR(30), 
	role VARCHAR(20), password VARCHAR(4), 
	username VARCHAR(100), 
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);